//This file is generated by tools!
//Please do not modify this file!
public class DataDefine {

	public const int Duties_Duties_Id = 0;
	public const int Duties_Duties_Type = 1;
	public const int Duties_Duties_Name = 2;
	public const int Duties_Duties_PreId = 3;
	public const int Duties_Duties_SkillName = 4;
	public const int Duties_Duties_Desc = 5;
	public const int Duties_Duties_SkillIcon = 6;
	public const int Duties_Duties_条件数值 = 7;
	public const int Duties_Duties_Salary = 8;
	public const int Duties_Duties_loyal = 9;
	public const int Duties_Duties_AddedDesign = 10;
	public const int Duties_Duties_AddedTech = 11;
	public const int Duties_Duties_AddedArt = 12;
	public const int Duties_Boss_Id = 0;
	public const int Duties_Boss_Type = 1;
	public const int Duties_Boss_Name = 2;
	public const int Duties_Boss_PreId = 3;
	public const int Duties_Boss_SkillName = 4;
	public const int Duties_Boss_Desc = 5;
	public const int Duties_Boss_SkillIcon = 6;
	public const int Duties_Boss_Exp = 7;
	public const int Duties_Boss_Money = 8;
	public const int Duties_Boss_HotValue = 9;
	public const int Duties_Boss_CostMoney = 10;
	public const int Duties_Boss_Illustrationname = 11;
	public const int Duties_BossDutiesUnlock_Id = 0;
	public const int Duties_BossDutiesUnlock_Type = 1;
	public const int Duties_BossDutiesUnlock_Desc = 2;
	public const int Duties_BossDutiesUnlock_DescId = 3;
	public const int Duties_BossDutiesUnlock_Money = 4;
	public const int Duties_BossDutiesUnlockItemInfo_Id = 0;
	public const int Duties_BossDutiesUnlockItemInfo_Name = 1;
	public const int Duties_BossDutiesUnlockItemInfo_Desc = 2;
	public const int GameObject_GameKey_Id = 0;
	public const int GameObject_GameKey_Texture = 1;
	public const int GameObject_GameKey_Name = 2;
	public const int GameObject_GameKey_Desc = 3;
	public const int GameObject_GameKey_Effect = 4;
	public const int GameObject_GameKey_ObjName = 5;
	public const int GameObject_Prop_Id = 0;
	public const int GameObject_Prop_ObjName = 1;

}